#include <bits/stdc++.h>
using namespace std;

void pht() {
    ios::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}

long long longest(vector <long long> arr, long long num) {
    for(int i = 1; i < num);
    return 0;
}

int main() {
    pht();
    long long x, n;
    cin >> x >> n;
    vector <long long> lights(n);
    for(int i = 0; i < n; i++) {
        cin >> lights[n];
    }
    set <long long> setOf;
    for(int i = 0; i < x; i++) {
        setOf.insert(longest(lights, lights[i]));
    }
    return 0;
}